CREATE TABLE Customers (
	id_customer INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(41) NOT NULL DEFAULT '',
	balance DECIMAL(15,5) NOT NULL DEFAULT 0.00000
	firstname VARCHAR(25) DEFAULT NULL,
);

CREATE TABLE Accounts (
  id_account INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	id VARCHAR(32) NOT NULL DEFAULT '',
	password VARCHAR(16),
	balance DECIMAL(15,5) NOT NULL DEFAULT 0.00000,
	billing_model TINYINT NOT NULL DEFAULT 0,
	id_customer INT UNSIGNED NOT NULL DEFAULT 0
);
